spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auction?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: root
    password: 3579

mybatis:
  mapper-locations: mapper/**/*.xml

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456789
    key-store-type: PKCS12

  port: 443

  tomcat:
    protocol_header: x-forwarded-proto
    remote_ip_header: x-forwarded-for

